# Generated by Django 3.2.16 on 2022-12-12 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='descripption',
            new_name='description',
        ),
    ]
